<?php

namespace SMSGateway;

if (!defined('ABSPATH')) {
    exit;
}

/**
 * BrqSMS gateway.
 *
 * Docs: https://dash.brqsms.com/developers
 * Uses the BrqSMS v3 REST API (Bearer token auth, JSON payloads, UTF-8).
 *
 * The verification message (which already contains the OTP generated by the
 * plugin) is delivered as an SMS through the BrqSMS SMS API endpoint.
 */
class BrqSMS {

    const API_ENDPOINT = 'https://dash.brqsms.com/api/v3/sms/send';

    /**
     * @param array  $gateway_fields  Credentials stored under option digit_brqsms.
     * @param string $mobile          Full recipient number ($countrycode . $mobile).
     * @param string $message         Message body (already contains the OTP).
     * @param bool   $test_call       When true returns the raw API response / error.
     *
     * @return bool|string
     */
    public static function sendSMS($gateway_fields, $mobile, $message, $test_call) {
        $api_token = isset($gateway_fields['api_token']) ? trim($gateway_fields['api_token']) : '';
        $sender    = isset($gateway_fields['sender']) ? trim($gateway_fields['sender']) : '';

        // Fail fast on missing credentials so the admin gets a clear message.
        if ($api_token === '') {
            return $test_call ? 'BrqSMS error: API Token is not configured.' : false;
        }

        $recipient = self::normalize_recipient($mobile);
        if ($recipient === '') {
            return $test_call ? 'BrqSMS error: Recipient phone number is empty or invalid.' : false;
        }

        return self::process_sms($api_token, $sender, $recipient, $message, $test_call);
    }

    /**
     * Strip the leading "+" and keep digits only (BrqSMS expects a bare MSISDN).
     */
    protected static function normalize_recipient($mobile) {
        return preg_replace('/\D+/', '', (string) $mobile);
    }

    /**
     * BrqSMS treats non-GSM (e.g. Arabic) content as unicode. Detect it so the
     * message is sent with the right encoding instead of being mangled.
     */
    protected static function message_type($message) {
        // If the message contains any character outside the basic ASCII range,
        // treat it as unicode (covers Arabic and other non-Latin scripts).
        return preg_match('/[^\x00-\x7F]/', $message) ? 'unicode' : 'plain';
    }

    public static function process_sms($api_token, $sender, $recipient, $message, $test_call) {

        $data = array(
            'recipient' => $recipient,
            'sender_id' => $sender,
            'type'      => self::message_type($message),
            'message'   => $message,
        );

        $payload = json_encode($data);
        if ($payload === false) {
            return $test_call ? 'BrqSMS error: Unable to encode request payload.' : false;
        }

        $curl = curl_init();

        curl_setopt($curl, CURLOPT_URL, self::API_ENDPOINT);
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt(
            $curl,
            CURLOPT_HTTPHEADER,
            array(
                'Content-Type: application/json',
                'Accept: application/json',
                'Authorization: Bearer ' . $api_token,
            )
        );
        curl_setopt($curl, CURLOPT_POST, 1);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $payload);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_TIMEOUT, 30);

        $result      = curl_exec($curl);
        $code        = curl_getinfo($curl, CURLINFO_HTTP_CODE);
        $curl_errno  = curl_errno($curl);
        $curl_error  = curl_error($curl);
        curl_close($curl);

        if ($test_call) {
            if ($curl_errno !== 0) {
                return 'BrqSMS connection error (' . $curl_errno . '): ' . $curl_error;
            }
            // Surface the HTTP status alongside the body to make debugging easy.
            return 'HTTP ' . $code . ' - ' . $result;
        }

        if ($curl_errno !== 0) {
            return false;
        }

        $is_http_ok = (200 <= $code && $code < 300);

        // BrqSMS returns {"status":"success", ...} on success.
        $decoded = json_decode($result, true);
        if (is_array($decoded) && isset($decoded['status'])) {
            return $decoded['status'] === 'success';
        }

        return $is_http_ok;
    }
}
