<?php

namespace SMSGateway;

if (!defined('ABSPATH')) {
    exit;
}

/**
 * BrqSMS gateway.
 *
 * Docs: https://dash.brqsms.com/developers
 * Uses the BrqSMS v3 REST API (Bearer token auth, JSON payloads, UTF-8).
 *
 * Sends the verification message as a plain SMS through the
 * BrqSMS SMS API endpoint, which carries the OTP text generated by the plugin.
 */
class BrqSMS {

    const API_ENDPOINT = 'https://dash.brqsms.com/api/v3/sms/send';

    /**
     * @param array  $gateway_fields  Credentials stored under option digit_brqsms.
     * @param string $mobile          Full recipient number ($countrycode . $mobile).
     * @param string $message         Message body (already contains the OTP).
     * @param bool   $test_call       When true returns the raw API response.
     *
     * @return bool|string
     */
    public static function sendSMS($gateway_fields, $mobile, $message, $test_call) {
        $api_token = isset($gateway_fields['api_token']) ? trim($gateway_fields['api_token']) : '';
        $sender    = isset($gateway_fields['sender']) ? trim($gateway_fields['sender']) : '';

        return self::process_sms($api_token, $sender, $mobile, $message, $test_call);
    }

    public static function process_sms($api_token, $sender, $mobile, $message, $test_call) {

        // BrqSMS expects the recipient without a leading "+".
        $recipient = ltrim($mobile, '+');

        $data = array(
            'recipient' => $recipient,
            'sender_id' => $sender,
            'type'      => 'plain',
            'message'   => $message,
        );

        $curl = curl_init();

        curl_setopt($curl, CURLOPT_URL, self::API_ENDPOINT);
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt(
            $curl,
            CURLOPT_HTTPHEADER,
            array(
                'Content-Type: application/json',
                'Accept: application/json',
                'Authorization: Bearer ' . $api_token,
            )
        );
        curl_setopt($curl, CURLOPT_POST, 1);
        curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($data));
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_TIMEOUT, 30);

        $result     = curl_exec($curl);
        $code       = curl_getinfo($curl, CURLINFO_HTTP_CODE);
        $curl_error = curl_errno($curl);
        curl_close($curl);

        if ($test_call) {
            if ($curl_error !== 0) {
                return 'curl error: ' . $curl_error;
            }
            return $result;
        }

        if ($curl_error !== 0) {
            return false;
        }

        $is_http_ok = (200 <= $code && $code < 300);

        // BrqSMS returns {"status":"success", ...} on success.
        $decoded = json_decode($result, true);
        if (is_array($decoded) && isset($decoded['status'])) {
            return $decoded['status'] === 'success';
        }

        return $is_http_ok;
    }
}
